### PR TITLE
Clarify "glitch" as a technical term

### PR DESCRIPTION
**Pull request by dead-claudia**
Related to #123. I thought it'd at least be worth taking the step of clarifying it as a technical term of art in the meantime until someone rewrites the explainer.

### CODE REVIEW

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by fabiospampinato** [comment]
> If rendering is done immediately when a Signal is set, it may expose incomplete application state to the end user.

I'm not sure I see this, how would it happen?

Unless there is a bug somewhere I don't think you'd get into a state where logging a value and its computed double won't make sense, for example.

**Comment by dead-claudia** [comment]
> > If rendering is done immediately when a Signal is set, it may expose incomplete application state to the end user.
> 
> 
> 
> I'm not sure I see this, how would it happen?
> 
> 
> 
> Unless there is a bug somewhere I don't think you'd get into a state where logging a value and its computed double won't make sense, for example.
> 
> 
> 
> Nor the browser will be rendering (except for scrolling and some things like that?) while the main thread is blocked, I think.

I didn't write that prose (or any prose, for that matter). I just linkified a word in a few places.

**Comment by dead-claudia** [comment]
@fabiospampinato I didn't write that prose (or any prose, for that matter). This PR is just adding inline links in a few places.

**Review by littledan — COMMENTED** [review]
Thanks for the link but at least on my phone, Wikipedia seems to insist on the /wiki/, so maybe instead link to https://en.wikipedia.org/wiki/Reactive_programming#Glitches

**Comment by dead-claudia** [comment]
@littledan Thanks for the catch! Pushed a fix.

**Review by littledan — APPROVED** [review]

**Pull request merged**
